# Generated by Django 2.0.5 on 2018-05-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180514_0623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['position_id']},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['position_id']},
        ),
        migrations.AlterField(
            model_name='card',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.Column'),
        ),
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='api.Board'),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set(),
        ),
    ]
